name: demopico
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  provider: ^6.1.2
  intl: ^0.19.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.9.0
  dartz: ^0.10.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  get_it: ^7.7.0
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  icon_decoration: ^2.0.2
  flutter_rating_bar: ^4.0.0
  widget_to_marker: ^1.0.6
  shared_preferences: ^2.3.3
  

dev_dependencies:
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
      sdk: flutter
  flutter_driver:
      sdk: flutter
  test: ^1.25.7
  build_runner: ^2.4.13
  mocktail: ^1.0.4

flutter:
    uses-material-design: true
    assets:
      - assets/images/skatepico-icon.png
      - assets/images/containerLogin.jpg
      - assets/images/containerCadastro.jpg
      - assets/images/iconPico.png
      - assets/images/progresso1.png
      - assets/images/progresso2.png
      - assets/images/progresso3.png
      - assets/images/progresso4.png
      - assets/images/userPhoto.png
      - assets/images/Location.png 
      - assets/images/icons/