name: demopico
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  provider: ^6.1.2
  intl: ^0.19.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.9.0
  dartz: ^0.10.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
      - assets/images/skatepico-icon.png
      - assets/images/containerLogin.jpg
      - assets/images/containerCadastro.jpg
