// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHUyAejc79CWSY1Zb-6Vqs_r1B51dIR9E',
    appId: '1:495399023145:android:5c56e3301f8a2187546238',
    messagingSenderId: '495399023145',
    projectId: 'pico-skatepico',
    storageBucket: 'pico-skatepico.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6QLRRNyBiLReg9gIbwXV9WovKTkUPq1E',
    appId: '1:495399023145:ios:7ea702e0d60eece9546238',
    messagingSenderId: '495399023145',
    projectId: 'pico-skatepico',
    storageBucket: 'pico-skatepico.appspot.com',
    iosBundleId: 'com.example.demopico',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyD1-BgFXNQcgU589XVeiluCl1g8AK5FQbg",
      authDomain: "pico-skatepico.firebaseapp.com",
      projectId: "pico-skatepico",
      storageBucket: "pico-skatepico.appspot.com",
      messagingSenderId: "495399023145",
      appId: "1:495399023145:web:c4b083cbcb1da3eb546238",
      measurementId: "G-51K65SHSYJ");
}
