name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs: 
  flutter_test:
    name: Execute flutter test and flutter analyze
    runs-on: ubuntu-latest
    env:
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with: 
          java-version: '17' # minimum version for this aplication
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.1  
          channel: stable


      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test